name: Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
      - name: Get package version
        id: package-version
        run: |
          echo "VERSION=$(git describe --tags --always 2>/dev/null)" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          mkdir build && go build -ldflags '-X main.Version=${{ steps.package-version.outputs.VERSION }}' -o build/coredock
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker Builder
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # platforms: linux/amd64, linux/arm64
          tags: |
            ghcr.io/${{ github.actor }}/coredock:latest
            ghcr.io/${{ github.actor }}/coredock:v${{ steps.package-version.outputs.VERSION }}
